In [2]:
!pip install requests beautifulsoup4 pandas openpyxl lxml

Requirement already satisfied: requests in c:\users\sadasiv\anaconda3\lib\site-packages (2.32.5)
Requirement already satisfied: beautifulsoup4 in c:\users\sadasiv\anaconda3\lib\site-packages (4.13.5)
Requirement already satisfied: pandas in c:\users\sadasiv\anaconda3\lib\site-packages (2.3.3)
Requirement already satisfied: openpyxl in c:\users\sadasiv\anaconda3\lib\site-packages (3.1.5)
Requirement already satisfied: lxml in c:\users\sadasiv\anaconda3\lib\site-packages (5.3.0)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\users\sadasiv\anaconda3\lib\site-packages (from requests) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in c:\users\sadasiv\anaconda3\lib\site-packages (from requests) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\sadasiv\anaconda3\lib\site-packages (from requests) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\sadasiv\anaconda3\lib\site-packages (from requests) (2026.6.17)
Requirement already satisfied: soupsieve>1.2 in c:\users\sadasiv\anaconda3\lib\site-packages (from beautifulsoup4) (2.5)
Requirement already satisfied: typing-extensions>=4.0.0 in c:\users\sadasiv\anaconda3\lib\site-packages (from beautifulsoup4) (4.15.0)
Requirement already satisfied: numpy>=1.26.0 in c:\users\sadasiv\anaconda3\lib\site-packages (from pandas) (2.3.5)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\sadasiv\anaconda3\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\sadasiv\anaconda3\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\sadasiv\anaconda3\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: et-xmlfile in c:\users\sadasiv\anaconda3\lib\site-packages (from openpyxl) (2.0.0)
Requirement already satisfied: six>=1.5 in c:\users\sadasiv\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [3]:
import requests
from bs4 import BeautifulSoup
import pandas as pd
import time

In [4]:
url = "https://books.toscrape.com/"

headers = {
    "User-Agent": "Mozilla/5.0"
}

response = requests.get(url, headers=headers)

print("Status Code:", response.status_code)

Status Code: 200

In [5]:
soup = BeautifulSoup(response.text, "html.parser")

print(soup.title.text)

    All products | Books to Scrape - Sandbox

In [6]:
books = soup.find_all("article", class_="product_pod")

print("Total Books on First Page:", len(books))

Total Books on First Page: 20

In [7]:
book = books[0]

title = book.h3.a["title"]

price = book.find("p", class_="price_color").text

availability = book.find("p", class_="instock availability").text.strip()

rating = book.find("p")["class"][1]

print("Title:", title)
print("Price:", price)
print("Availability:", availability)
print("Rating:", rating)

Title: A Light in the Attic
Price: Â£51.77
Availability: In stock
Rating: Three

In [8]:
rating_map = {
    "One": 1,
    "Two": 2,
    "Three": 3,
    "Four": 4,
    "Five": 5
}

numeric_rating = rating_map[rating]

print("Numeric Rating:", numeric_rating)

Numeric Rating: 3

In [9]:
product_name = []
price = []
rating = []
availability = []
product_url = []

In [10]:
rating_map = {
    "One": 1,
    "Two": 2,
    "Three": 3,
    "Four": 4,
    "Five": 5
}

for book in books:

    # Product Name
    title = book.h3.a["title"]

    # Price
    book_price = book.find("p", class_="price_color").text.replace("£", "")

    # Availability
    stock = book.find("p", class_="instock availability").text.strip()

    # Rating
    rating_text = book.find("p")["class"][1]
    book_rating = rating_map[rating_text]

    # Product URL
    link = "https://books.toscrape.com/catalogue/" + book.h3.a["href"].replace("../", "")

    product_name.append(title)
    price.append(book_price)
    availability.append(stock)
    rating.append(book_rating)
    product_url.append(link)

In [11]:
df = pd.DataFrame({
    "Product_Name": product_name,
    "Price": price,
    "Availability": availability,
    "Rating": rating,
    "Product_URL": product_url
})

In [12]:
df.head()

,Product_Name,Price,Availability,Rating,Product_URL
0,A Light in the Attic,Â51.77,In stock,3,https://books.toscrape.com/catalogue/catalogue...
1,Tipping the Velvet,Â53.74,In stock,1,https://books.toscrape.com/catalogue/catalogue...
2,Soumission,Â50.10,In stock,1,https://books.toscrape.com/catalogue/catalogue...
3,Sharp Objects,Â47.82,In stock,4,https://books.toscrape.com/catalogue/catalogue...
4,Sapiens: A Brief History of Humankind,Â54.23,In stock,5,https://books.toscrape.com/catalogue/catalogue...

In [13]:
df.shape

(20, 5)

In [14]:
import requests
from bs4 import BeautifulSoup
import pandas as pd
import time

product_name = []
price = []
rating = []
availability = []
product_url = []

In [15]:
rating_map = {
    "One": 1,
    "Two": 2,
    "Three": 3,
    "Four": 4,
    "Five": 5
}

In [16]:
base_url = "https://books.toscrape.com/catalogue/page-{}.html"

headers = {
    "User-Agent": "Mozilla/5.0"
}

for page in range(1, 51):

    print(f"Scraping Page {page}")

    url = base_url.format(page)

    response = requests.get(url, headers=headers)

    soup = BeautifulSoup(response.text, "html.parser")

    books = soup.find_all("article", class_="product_pod")

    for book in books:

        # Product Name
        title = book.h3.a["title"]

        # Price
        book_price = book.find("p", class_="price_color").text.replace("£", "")

        # Availability
        stock = book.find("p", class_="instock availability").text.strip()

        # Rating
        rating_text = book.find("p")["class"][1]
        book_rating = rating_map[rating_text]

        # Product URL
        link = "https://books.toscrape.com/catalogue/" + book.h3.a["href"].replace("../", "")

        product_name.append(title)
        price.append(book_price)
        availability.append(stock)
        rating.append(book_rating)
        product_url.append(link)

    time.sleep(1)

print("Scraping Completed")

Scraping Page 1
Scraping Page 2
Scraping Page 3
Scraping Page 4
Scraping Page 5
Scraping Page 6
Scraping Page 7
Scraping Page 8
Scraping Page 9
Scraping Page 10
Scraping Page 11
Scraping Page 12
Scraping Page 13
Scraping Page 14
Scraping Page 15
Scraping Page 16
Scraping Page 17
Scraping Page 18
Scraping Page 19
Scraping Page 20
Scraping Page 21
Scraping Page 22
Scraping Page 23
Scraping Page 24
Scraping Page 25
Scraping Page 26
Scraping Page 27
Scraping Page 28
Scraping Page 29
Scraping Page 30
Scraping Page 31
Scraping Page 32
Scraping Page 33
Scraping Page 34
Scraping Page 35
Scraping Page 36
Scraping Page 37
Scraping Page 38
Scraping Page 39
Scraping Page 40
Scraping Page 41
Scraping Page 42
Scraping Page 43
Scraping Page 44
Scraping Page 45
Scraping Page 46
Scraping Page 47
Scraping Page 48
Scraping Page 49
Scraping Page 50
Scraping Completed

In [17]:
df = pd.DataFrame({
    "Product_Name": product_name,
    "Price": price,
    "Availability": availability,
    "Rating": rating,
    "Product_URL": product_url
})

In [18]:
df.head()

,Product_Name,Price,Availability,Rating,Product_URL
0,A Light in the Attic,Â51.77,In stock,3,https://books.toscrape.com/catalogue/a-light-i...
1,Tipping the Velvet,Â53.74,In stock,1,https://books.toscrape.com/catalogue/tipping-t...
2,Soumission,Â50.10,In stock,1,https://books.toscrape.com/catalogue/soumissio...
3,Sharp Objects,Â47.82,In stock,4,https://books.toscrape.com/catalogue/sharp-obj...
4,Sapiens: A Brief History of Humankind,Â54.23,In stock,5,https://books.toscrape.com/catalogue/sapiens-a...

In [19]:
df.shape

(1000, 5)

In [20]:
df.info

<bound method DataFrame.info of                                           Product_Name   Price Availability  \
0                                 A Light in the Attic  Â51.77     In stock
1                                   Tipping the Velvet  Â53.74     In stock
2                                           Soumission  Â50.10     In stock
3                                        Sharp Objects  Â47.82     In stock
4                Sapiens: A Brief History of Humankind  Â54.23     In stock
..                                                 ...     ...          ...
995  Alice in Wonderland (Alice's Adventures in Won...  Â55.53     In stock
996   Ajin: Demi-Human, Volume 1 (Ajin: Demi-Human #1)  Â57.06     In stock
997  A Spy's Devotion (The Regency Spies of London #1)  Â16.97     In stock
998                1st to Die (Women's Murder Club #1)  Â53.98     In stock
999                 1,000 Places to See Before You Die  Â26.08     In stock

     Rating                                        Product_URL
0         3  https://books.toscrape.com/catalogue/a-light-i...
1         1  https://books.toscrape.com/catalogue/tipping-t...
2         1  https://books.toscrape.com/catalogue/soumissio...
3         4  https://books.toscrape.com/catalogue/sharp-obj...
4         5  https://books.toscrape.com/catalogue/sapiens-a...
..      ...                                                ...
995       1  https://books.toscrape.com/catalogue/alice-in-...
996       4  https://books.toscrape.com/catalogue/ajin-demi...
997       5  https://books.toscrape.com/catalogue/a-spys-de...
998       1  https://books.toscrape.com/catalogue/1st-to-di...
999       5  https://books.toscrape.com/catalogue/1000-plac...

[1000 rows x 5 columns]>

In [22]:
df.to_csv("capstone project raw_products data.csv", index=False)

In [23]:
#here is add manually some data fullfill my project

In [25]:
import pandas as pd
import numpy as np
import random

# Read your scraped CSV
df = pd.read_csv("capstone project raw_products data.csv")

# Check data
df.head()

,Product_Name,Price,Availability,Rating,Product_URL
0,A Light in the Attic,Â51.77,In stock,3,https://books.toscrape.com/catalogue/a-light-i...
1,Tipping the Velvet,Â53.74,In stock,1,https://books.toscrape.com/catalogue/tipping-t...
2,Soumission,Â50.10,In stock,1,https://books.toscrape.com/catalogue/soumissio...
3,Sharp Objects,Â47.82,In stock,4,https://books.toscrape.com/catalogue/sharp-obj...
4,Sapiens: A Brief History of Humankind,Â54.23,In stock,5,https://books.toscrape.com/catalogue/sapiens-a...

In [26]:
df.drop(columns=["Product_URL"], inplace=True)

In [41]:
df.columns

Index(['Book_ID', 'Book_Title', 'Selling_Price', 'Books_In_Stock',
       'Customer_Rating', 'Genre', 'Publisher', 'Original_Price'],
      dtype='object')

In [46]:
df["Selling_Price"] = (
    df["Selling_Price"]
    .astype(str)
    .str.replace("Â", "", regex=False)
    .str.replace("£", "", regex=False)
    .str.replace(",", "", regex=False)
    .str.strip()
)

df["Selling_Price"] = pd.to_numeric(df["Selling_Price"], errors="coerce")

In [47]:
df.head()

,Book_ID,Book_Title,Selling_Price,Books_In_Stock,Customer_Rating,Genre,Publisher,Original_Price
0,BK00001,A Light in the Attic,5953.55,In stock,3,Mystery,Rupa Publications,8779.13
1,BK00002,Tipping the Velvet,6180.10,In stock,1,Classic,Cambridge University Press,8323.75
2,BK00003,Soumission,5761.50,In stock,1,Travel,SAGE Publications,8161.57
3,BK00004,Sharp Objects,5499.30,In stock,4,Travel,SAGE Publications,7831.85
4,BK00005,Sapiens: A Brief History of Humankind,6236.45,In stock,5,Mystery,Simon & Schuster,6893.67

In [48]:
df["Discount_Percentage"] = (
    (
        df["Original_Price"] - df["Selling_Price"]
    ) / df["Original_Price"] * 100
).round(2)

In [49]:
df[["Selling_Price","Original_Price","Discount_Percentage"]].head()

   Selling_Price  Original_Price  Discount_Percentage
0        5953.55         8779.13                32.19
1        6180.10         8323.75                25.75
2        5761.50         8161.57                29.41
3        5499.30         7831.85                29.78
4        6236.45         6893.67                 9.53

In [50]:
book_sellers = [
    "Book World",
    "Readers Hub",
    "Book Bazaar",
    "Book Planet",
    "Book Corner",
    "Readers Choice",
    "Library Store",
    "Book House",
    "Online Book Shop",
    "Book Galaxy"
]

df["Book_Seller"] = np.random.choice(book_sellers, len(df))

In [51]:
df["Delivery_Days"] = np.random.randint(1,8,len(df))

In [52]:
df["Free_Delivery"] = np.random.choice(
    ["Yes","No"],
    len(df),
    p=[0.80,0.20]
)

In [53]:
df["Premium_Delivery"] = np.random.choice(
    ["Yes","No"],
    len(df),
    p=[0.70,0.30]
)

In [54]:
df["Wishlist_Count"] = np.random.randint(0,2500,len(df))

In [55]:
df["Copies_Sold"] = np.random.randint(50,8000,len(df))

In [56]:
df["Return_Rate"] = np.round(
    np.random.uniform(0,10,len(df)),
    2
)

In [57]:
df["Publication_Year"] = np.random.randint(2015,2026,len(df))

In [58]:
cities = [
    "Hyderabad",
    "Bengaluru",
    "Chennai",
    "Mumbai",
    "Delhi",
    "Pune",
    "Kolkata",
    "Ahmedabad",
    "Jaipur",
    "Lucknow",
    "Bhubaneswar",
    "Visakhapatnam"
]

df["Warehouse_City"] = np.random.choice(cities, len(df))

In [60]:
conditions = [
    df["Customer_Rating"] >= 4,
    df["Customer_Rating"] >= 3
]

choices = [
    "High",
    "Medium"
]

df["Customer_Satisfaction"] = np.select(
    conditions,
    choices,
    default="Low"
)

In [62]:
print(df.columns.tolist())

['Book_ID', 'Book_Title', 'Selling_Price', 'Books_In_Stock', 'Customer_Rating', 'Genre', 'Publisher', 'Original_Price', 'Discount_Percentage', 'Book_Seller', 'Delivery_Days', 'Free_Delivery', 'Premium_Delivery', 'Wishlist_Count', 'Copies_Sold', 'Return_Rate', 'Publication_Year', 'Warehouse_City', 'Customer_Satisfaction']

In [63]:
import numpy as np

df["Review_Count"] = np.random.randint(20, 5000, len(df))

In [64]:
df = df[
    [
        "Book_ID",
        "Book_Title",
        "Genre",
        "Publisher",
        "Selling_Price",
        "Original_Price",
        "Discount_Percentage",
        "Customer_Rating",
        "Review_Count",
        "Books_In_Stock",
        "Book_Seller",
        "Delivery_Days",
        "Free_Delivery",
        "Premium_Delivery",
        "Wishlist_Count",
        "Copies_Sold",
        "Return_Rate",
        "Publication_Year",
        "Warehouse_City",
        "Customer_Satisfaction"
    ]
]

In [65]:
print(df.columns.tolist())

['Book_ID', 'Book_Title', 'Genre', 'Publisher', 'Selling_Price', 'Original_Price', 'Discount_Percentage', 'Customer_Rating', 'Review_Count', 'Books_In_Stock', 'Book_Seller', 'Delivery_Days', 'Free_Delivery', 'Premium_Delivery', 'Wishlist_Count', 'Copies_Sold', 'Return_Rate', 'Publication_Year', 'Warehouse_City', 'Customer_Satisfaction']

In [66]:
df.to_csv("Online_Book_Store_Analytics.csv", index=False)

print("Dataset Saved Successfully!")

Dataset Saved Successfully!